name: hello_books
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #SharedPreference-persisting theme selection
  shared_preferences: ^2.0.7
  moor: any
  sqlite3_flutter_libs: ^0.5.0
  #Helper to find the database path on mobile
  path_provider: ^2.0.3
  path: ^1.8.0
  http: ^0.13.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  moor_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/flutter.png
    - assets/book_cover.png

  fonts:
    - family: Pangolin
      fonts:
        - asset: assets/fonts/Pangolin-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
